"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
DATA_FILES = [
    ('', ['cfg.base.yml']),
    ('gui', ['gui/controller.ini', 'gui/controller.kv', 'gui/settings.yml']),
    ('gui/data', ['gui/data/fontawesome-webfont.ttf']),
]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    description='Fetch new tv episodes and movies from put.io',
    name='Fetcher',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    version='1.0',
)
