- type: string
  title: API Key
  key: api_key
  section: put.io
- type: string
  title: API Secret
  key: api_secret
  section: put.io
- type: path
  title: Download Path
  key: download_path
  section: put.io
